package com.app.umkaSchool.service.impl;

import com.app.umkaSchool.dto.student.CreateStudentRequest;
import com.app.umkaSchool.dto.student.StudentResponse;
import com.app.umkaSchool.dto.student.UpdateStudentRequest;
import com.app.umkaSchool.model.*;
import com.app.umkaSchool.model.enums.GuardianRelationship;
import com.app.umkaSchool.repository.*;
import com.app.umkaSchool.service.StudentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class StudentServiceImpl implements StudentService {
    private static final Logger logger = LoggerFactory.getLogger(StudentServiceImpl.class);

    private final StudentRepository studentRepository;
    private final AppUserRepository userRepository;
    private final GuardianRepository guardianRepository;
    private final TeacherRepository teacherRepository;
    private final StudentGroupRepository groupRepository;
    private final PasswordEncoder passwordEncoder;

    @Autowired
    public StudentServiceImpl(StudentRepository studentRepository,
                              AppUserRepository userRepository,
                              GuardianRepository guardianRepository,
                              TeacherRepository teacherRepository,
                              StudentGroupRepository groupRepository,
                              PasswordEncoder passwordEncoder) {
        this.studentRepository = studentRepository;
        this.userRepository = userRepository;
        this.guardianRepository = guardianRepository;
        this.teacherRepository = teacherRepository;
        this.groupRepository = groupRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    @Transactional
    public StudentResponse createStudent(CreateStudentRequest request) {
        logger.info("Creating new student: {}", request.getEmail());

        // Find existing user by email
        AppUser user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new IllegalArgumentException("User with email " + request.getEmail() + " not found. User must be created first via signup."));

        // Check if student already exists for this user
        if (studentRepository.findByUser_Id(user.getId()).isPresent()) {
            throw new IllegalArgumentException("Student profile already exists for this user");
        }

        // Update user information
        user.setFirstName(request.getFirstName());
        user.setLastName(request.getLastName());

        // Update avatar URL if provided
        if (request.getAvatarUrl() != null && !request.getAvatarUrl().isEmpty()) {
            user.setAvatarUrl(request.getAvatarUrl());
        }

        user = userRepository.save(user);

        // Create or get guardian
        Guardian guardian = guardianRepository.findByEmail(request.getGuardianEmail())
                .orElseGet(() -> {
                    Guardian newGuardian = new Guardian();
                    // ID will be auto-generated by Hibernate
                    newGuardian.setFirstName(request.getGuardianFirstName());
                    newGuardian.setLastName(request.getGuardianLastName());
                    newGuardian.setEmail(request.getGuardianEmail());
                    newGuardian.setPhone(request.getGuardianPhone());
                    newGuardian.setRelationship(GuardianRelationship.valueOf(request.getGuardianRelationship()));
                    return guardianRepository.save(newGuardian);
                });


        // Create student
        Student student = new Student();
        student.setId(user.getId());
        student.setUser(user);
        student.setDateOfBirth(request.getDateOfBirth());
        student.setGuardian(guardian);

        // Assign teacher if provided
        if (request.getTeacherId() != null) {
            Teacher teacher = teacherRepository.findById(request.getTeacherId())
                    .orElseThrow(() -> new IllegalArgumentException("Teacher not found"));
            student.setTeacher(teacher);
        }

        // Assign group if provided
        if (request.getGroupId() != null) {
            StudentGroup group = groupRepository.findById(request.getGroupId())
                    .orElseThrow(() -> new IllegalArgumentException("Group not found"));
            student.setGroup(group);
        }

        student = studentRepository.save(student);
        logger.info("Student created successfully: {}", student.getId());

        return mapToResponse(student);
    }

    @Override
    @Transactional
    public StudentResponse updateStudent(UUID studentId, UpdateStudentRequest request) {
        logger.info("Updating student: {}", studentId);

        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));

        AppUser user = student.getUser();

        // Update user info
        if (request.getFirstName() != null) {
            user.setFirstName(request.getFirstName());
        }
        if (request.getLastName() != null) {
            user.setLastName(request.getLastName());
        }
        if (request.getEmail() != null && !request.getEmail().equals(user.getEmail())) {
            if (userRepository.existsByEmail(request.getEmail())) {
                throw new IllegalArgumentException("Email already in use");
            }
            user.setEmail(request.getEmail());
        }

        // Update student info
        if (request.getDateOfBirth() != null) {
            student.setDateOfBirth(request.getDateOfBirth());
        }

        // Update teacher
        if (request.getTeacherId() != null) {
            Teacher teacher = teacherRepository.findById(request.getTeacherId())
                    .orElseThrow(() -> new IllegalArgumentException("Teacher not found"));
            student.setTeacher(teacher);
        }

        // Update group
        if (request.getGroupId() != null) {
            StudentGroup group = groupRepository.findById(request.getGroupId())
                    .orElseThrow(() -> new IllegalArgumentException("Group not found"));
            student.setGroup(group);
        }

        // Update guardian info
        Guardian guardian = student.getGuardian();
        if (request.getGuardianFirstName() != null) {
            guardian.setFirstName(request.getGuardianFirstName());
        }
        if (request.getGuardianLastName() != null) {
            guardian.setLastName(request.getGuardianLastName());
        }
        if (request.getGuardianEmail() != null) {
            guardian.setEmail(request.getGuardianEmail());
        }
        if (request.getGuardianPhone() != null) {
            guardian.setPhone(request.getGuardianPhone());
        }
        if (request.getGuardianRelationship() != null) {
            guardian.setRelationship(GuardianRelationship.valueOf(request.getGuardianRelationship()));
        }

        guardianRepository.save(guardian);
        userRepository.save(user);
        student = studentRepository.save(student);

        logger.info("Student updated successfully: {}", studentId);
        return mapToResponse(student);
    }

    @Override
    public StudentResponse getStudentById(UUID studentId) {
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));
        return mapToResponse(student);
    }

    @Override
    public StudentResponse getStudentByUserId(UUID userId) {
        Student student = studentRepository.findByUser_Id(userId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found for user"));
        return mapToResponse(student);
    }

    @Override
    public List<StudentResponse> getAllStudents() {
        return studentRepository.findAll().stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    public List<StudentResponse> getStudentsByTeacher(UUID teacherId) {
        return studentRepository.findByTeacherIdOrderByLastActivityDesc(teacherId).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    public List<StudentResponse> getStudentsByGroup(UUID groupId) {
        return studentRepository.findByGroupIdOrderByName(groupId).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public void deleteStudent(UUID studentId) {
        logger.info("Deleting student: {}", studentId);
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));

        AppUser user = student.getUser();
        studentRepository.delete(student);
        userRepository.delete(user);

        logger.info("Student deleted successfully: {}", studentId);
    }

    @Override
    @Transactional
    public void assignToTeacher(UUID studentId, UUID teacherId) {
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));
        Teacher teacher = teacherRepository.findById(teacherId)
                .orElseThrow(() -> new IllegalArgumentException("Teacher not found"));

        student.setTeacher(teacher);
        studentRepository.save(student);
    }

    @Override
    @Transactional
    public void assignToGroup(UUID studentId, UUID groupId) {
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));
        StudentGroup group = groupRepository.findById(groupId)
                .orElseThrow(() -> new IllegalArgumentException("Group not found"));

        student.setGroup(group);
        studentRepository.save(student);
    }

    @Override
    @Transactional
    public void updateLastActivity(UUID studentId) {
        Student student = studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));
        student.setLastActivityAt(ZonedDateTime.now());
        studentRepository.save(student);
    }

    @Override
    public Student getStudentEntity(UUID studentId) {
        return studentRepository.findById(studentId)
                .orElseThrow(() -> new IllegalArgumentException("Student not found"));
    }

    private StudentResponse mapToResponse(Student student) {
        AppUser user = student.getUser();
        Guardian guardian = student.getGuardian();

        StudentResponse.GuardianInfo guardianInfo = StudentResponse.GuardianInfo.builder()
                .id(guardian.getId())
                .firstName(guardian.getFirstName())
                .lastName(guardian.getLastName())
                .email(guardian.getEmail())
                .phone(guardian.getPhone())
                .relationship(guardian.getRelationship().name())
                .build();

        return StudentResponse.builder()
                .id(student.getId())
                .userId(user.getId())
                .firstName(user.getFirstName())
                .lastName(user.getLastName())
                .email(user.getEmail())
                .dateOfBirth(student.getDateOfBirth())
                .enrollmentDate(student.getEnrollmentDate())
                .lastActivityAt(student.getLastActivityAt())
                .teacherId(student.getTeacher() != null ? student.getTeacher().getId() : null)
                .teacherName(student.getTeacher() != null ?
                        student.getTeacher().getUser().getFirstName() + " " +
                                student.getTeacher().getUser().getLastName() : null)
                .groupId(student.getGroup() != null ? student.getGroup().getId() : null)
                .groupName(student.getGroup() != null ? student.getGroup().getName() : null)
                .groupCode(student.getGroup() != null ? student.getGroup().getCode() : null)
                .guardian(guardianInfo)
                .avatarUrl(user.getAvatarUrl())
                .build();
    }
}